language: java

install: true

#不能用自定义测试，不然测试不通过也会显示build成功
script: "mvn cobertura:cobertura"

#代码覆盖
after_build:
  - bash <(curl -s https://codecov.io/bash)

jdk:
#  - oraclejdk8
  - openjdk8

git:
  depth: false

notifications:
  email:
    - 983804576@qq.com
  on_success: never  #never
  on_failure: always
