language: java

script:
  - mvn cobertura:cobertura

after_success:
#  - mvn cobertura:cobertura #此命令在测试不通过时会返回错误码 0
  - bash <(curl -s https://codecov.io/bash) #代码覆盖

jdk:
  - openjdk8

git:
  depth: false

notifications:
  email:
    - 983804576@qq.com
  on_success: never  #never
  on_failure: always
