language: java

script:
  - mvn test -B

after_success:
#  - mvn cobertura:cobertura #此命令 会运行测试 在测试失败时会返回错误码 0，继续生成测试报告
  - bash <(curl -s https://codecov.io/bash) -t 828e5def-08a3-4829-8214-acc9fec9be41 #代码覆盖

jdk:
  - openjdk8
  - openjdk9
  - openjdk11

git:
  depth: false

notifications:
  email:
    - 983804576@qq.com
  on_success: never  #never
  on_failure: always
