language: java

script:
  - mvn test -B

after_success:
#  - mvn cobertura:cobertura #此命令 会运行测试 在测试失败时会返回错误码 0，继续生成测试报告
  - mvn jacoco:report
  - bash <(curl -s https://codecov.io/bash) -t ${{ env.CODECOV-TOKEN.TOKEN }} #代码覆盖

jdk:
  - openjdk8
  - openjdk9
  - openjdk11

git:
  depth: false

notifications:
  email:
    - songjiangcq@qq.com
  on_success: always  #never
  on_failure: always
