language: java

#script: "mvn cobertura:cobertura"

##代码覆盖
#after_success:
#  - bash <(curl -s https://codecov.io/bash) -t 828e5def-08a3-4829-8214-acc9fec9be41

jdk:
  - oraclejdk8
  - openjdk8

git:
  depth: false

notifications:
  email:
      - 983804576@qq.com

after_success:
  - codecov
